all:
	cd array && make all
	cd char && make all
	cd math && make all
	cd meta && make all
	cd list && make all
	cd sorting && make all
	cd objects && make all
	cd x && make all


clean:
	cd array && make clean
	cd char && make clean
	cd math && make clean
	cd meta && make clean
	cd list && make clean
	cd sorting && make clean
	cd objects && make clean
	cd x && make clean


