all:
	cd array && make all
	cd char && make all
	cd math && make all
	cd meta && make all
	cd sorting && make all


clean:
	cd array && make clean
	cd char && make clean
	cd math && make clean
	cd meta && make clean
	cd sorting && make clean

