XMACRO(accept,accept, ACCEPT(form) ACCEPT(input))
XMACRO(accept_charset,accept-charset, ACCEPT(form))
XMACRO(accesskey,accesskey, GLOBAL)
XMACRO(action,action, ACCEPT(form))
XMACRO(align,align, ACCEPT(applet) ACCEPT(caption) ACCEPT(col) ACCEPT(colgroup) ACCEPT(hr) ACCEPT(iframe) ACCEPT(img) ACCEPT(table) ACCEPT(tbody) ACCEPT(td) ACCEPT(tfoot) ACCEPT(th) ACCEPT(thead) ACCEPT(tr))
XMACRO(allow,allow, ACCEPT(iframe))
XMACRO(alt,alt, ACCEPT(applet) ACCEPT(area) ACCEPT(img) ACCEPT(input))
XMACRO(async,async, ACCEPT(script))
XMACRO(autocapitalize,autocapitalize, GLOBAL)
XMACRO(autocomplete,autocomplete, ACCEPT(form) ACCEPT(input) ACCEPT(textarea))
XMACRO(autofocus,autofocus, ACCEPT(button) ACCEPT(input) ACCEPT(keygen) ACCEPT(select) ACCEPT(textarea))
XMACRO(autoplay,autoplay, ACCEPT(audio) ACCEPT(video))
XMACRO(bgcolor,bgcolor, ACCEPT(body) ACCEPT(col) ACCEPT(colgroup) ACCEPT(marquee) ACCEPT(table) ACCEPT(tbody) ACCEPT(tfoot) ACCEPT(td) ACCEPT(th) ACCEPT(tr))
XMACRO(border,border, ACCEPT(img) ACCEPT(object) ACCEPT(table))
XMACRO(buffered,buffered, ACCEPT(audio) ACCEPT(video))
XMACRO(challenge,challenge, ACCEPT(keygen))
XMACRO(charset,charset, ACCEPT(meta) ACCEPT(script))
XMACRO(checked,checked, ACCEPT(command) ACCEPT(input))
XMACRO(cite,cite, ACCEPT(blockquote) ACCEPT(del) ACCEPT(ins) ACCEPT(q))
XMACRO(class,class, GLOBAL)
XMACRO(code,code, ACCEPT(applet))
XMACRO(codebase,codebase, ACCEPT(applet))
XMACRO(color,color, ACCEPT(basefont) ACCEPT(font) ACCEPT(hr))
XMACRO(cols,cols, ACCEPT(textarea))
XMACRO(colspan,colspan, ACCEPT(td) ACCEPT(th))
XMACRO(content,content, ACCEPT(meta))
XMACRO(contenteditable,contenteditable, GLOBAL)
XMACRO(contextmenu,contextmenu, GLOBAL)
XMACRO(controls,controls, ACCEPT(audio) ACCEPT(video))
XMACRO(coords,coords, ACCEPT(area))
XMACRO(crossorigin,crossorigin, ACCEPT(audio) ACCEPT(img) ACCEPT(link) ACCEPT(script) ACCEPT(video))
XMACRO(csp,csp, ACCEPT(iframe))
XMACRO(data,data, ACCEPT(object))
XMACRO(data_,data-*, GLOBAL)
XMACRO(datetime,datetime, ACCEPT(del) ACCEPT(ins) ACCEPT(time))
XMACRO(decoding,decoding, ACCEPT(img))
XMACRO(default,default, ACCEPT(track))
XMACRO(defer,defer, ACCEPT(script))
XMACRO(dir,dir, GLOBAL)
XMACRO(dirname,dirname, ACCEPT(input) ACCEPT(textarea))
XMACRO(disabled,disabled, ACCEPT(button) ACCEPT(command) ACCEPT(fieldset) ACCEPT(input) ACCEPT(keygen) ACCEPT(optgroup) ACCEPT(option) ACCEPT(select) ACCEPT(textarea))
XMACRO(download,download, ACCEPT(a) ACCEPT(area))
XMACRO(draggable,draggable, GLOBAL)
XMACRO(dropzone,dropzone, GLOBAL)
XMACRO(enctype,enctype, ACCEPT(form))
XMACRO(for,for, ACCEPT(label) ACCEPT(output))
XMACRO(form,form, ACCEPT(button) ACCEPT(fieldset) ACCEPT(input) ACCEPT(keygen) ACCEPT(label) ACCEPT(meter) ACCEPT(object) ACCEPT(output) ACCEPT(progress) ACCEPT(select) ACCEPT(textarea))
XMACRO(formaction,formaction, ACCEPT(input) ACCEPT(button))
XMACRO(headers,headers, ACCEPT(td) ACCEPT(th))
XMACRO(height,height, ACCEPT(canvas) ACCEPT(embed) ACCEPT(iframe) ACCEPT(img) ACCEPT(input) ACCEPT(object) ACCEPT(video))
XMACRO(hidden,hidden, GLOBAL)
XMACRO(high,high, ACCEPT(meter))
XMACRO(href,href, ACCEPT(a) ACCEPT(area) ACCEPT(base) ACCEPT(link))
XMACRO(hreflang,hreflang, ACCEPT(a) ACCEPT(area) ACCEPT(link))
XMACRO(http_equiv,http-equiv, ACCEPT(meta))
XMACRO(icon,icon, ACCEPT(command))
XMACRO(id,id, GLOBAL)
XMACRO(importance,importance, ACCEPT(iframe) ACCEPT(img) ACCEPT(link) ACCEPT(script))
XMACRO(integrity,integrity, ACCEPT(link) ACCEPT(script))
XMACRO(ismap,ismap, ACCEPT(img))
XMACRO(itemprop,itemprop, GLOBAL)
XMACRO(keytype,keytype, ACCEPT(keygen))
XMACRO(kind,kind, ACCEPT(track))
XMACRO(label,label, ACCEPT(track))
XMACRO(lang,lang, GLOBAL)
XMACRO(language,language, ACCEPT(script))
XMACRO(lazyload,lazyload, ACCEPT(img) ACCEPT(iframe))
XMACRO(list,list, ACCEPT(input))
XMACRO(loop,loop, ACCEPT(audio) ACCEPT(bgsound) ACCEPT(marquee) ACCEPT(video))
XMACRO(low,low, ACCEPT(meter))
XMACRO(manifest,manifest, ACCEPT(html))
XMACRO(max,max, ACCEPT(input) ACCEPT(meter) ACCEPT(progress))
XMACRO(maxlength,maxlength, ACCEPT(input) ACCEPT(textarea))
XMACRO(minlength,minlength, ACCEPT(input) ACCEPT(textarea))
XMACRO(media,media, ACCEPT(a) ACCEPT(area) ACCEPT(link) ACCEPT(source) ACCEPT(style))
XMACRO(method,method, ACCEPT(form))
XMACRO(min,min, ACCEPT(input) ACCEPT(meter))
XMACRO(multiple,multiple, ACCEPT(input) ACCEPT(select))
XMACRO(muted,muted, ACCEPT(audio) ACCEPT(video))
XMACRO(name,name, ACCEPT(button) ACCEPT(form) ACCEPT(fieldset) ACCEPT(iframe) ACCEPT(input) ACCEPT(keygen) ACCEPT(object) ACCEPT(output) ACCEPT(select) ACCEPT(textarea) ACCEPT(map) ACCEPT(meta) ACCEPT(param))
XMACRO(novalidate,novalidate, ACCEPT(form))
XMACRO(open,open, ACCEPT(details))
XMACRO(optimum,optimum, ACCEPT(meter))
XMACRO(pattern,pattern, ACCEPT(input))
XMACRO(ping,ping, ACCEPT(a) ACCEPT(area))
XMACRO(placeholder,placeholder, ACCEPT(input) ACCEPT(textarea))
XMACRO(poster,poster, ACCEPT(video))
XMACRO(preload,preload, ACCEPT(audio) ACCEPT(video))
XMACRO(radiogroup,radiogroup, ACCEPT(command))
XMACRO(readonly,readonly, ACCEPT(input) ACCEPT(textarea))
XMACRO(referrerpolicy,referrerpolicy, ACCEPT(a) ACCEPT(area) ACCEPT(iframe) ACCEPT(img) ACCEPT(link) ACCEPT(script))
XMACRO(rel,rel, ACCEPT(a) ACCEPT(area) ACCEPT(link))
XMACRO(required,required, ACCEPT(input) ACCEPT(select) ACCEPT(textarea))
XMACRO(reversed,reversed, ACCEPT(ol))
XMACRO(rows,rows, ACCEPT(textarea))
XMACRO(rowspan,rowspan, ACCEPT(td) ACCEPT(th))
XMACRO(sandbox,sandbox, ACCEPT(iframe))
XMACRO(scope,scope, ACCEPT(th))
XMACRO(scoped,scoped, ACCEPT(style))
XMACRO(selected,selected, ACCEPT(option))
XMACRO(shape,shape, ACCEPT(a) ACCEPT(area))
XMACRO(size,size, ACCEPT(input) ACCEPT(select))
XMACRO(sizes,sizes, ACCEPT(link) ACCEPT(img) ACCEPT(source))
XMACRO(slot,slot, GLOBAL)
XMACRO(span,span, ACCEPT(col) ACCEPT(colgroup))
XMACRO(spellcheck,spellcheck, GLOBAL)
XMACRO(src,src, ACCEPT(audio) ACCEPT(embed) ACCEPT(iframe) ACCEPT(img) ACCEPT(input) ACCEPT(script) ACCEPT(source) ACCEPT(track) ACCEPT(video))
XMACRO(srcdoc,srcdoc, ACCEPT(iframe))
XMACRO(srclang,srclang, ACCEPT(track))
XMACRO(srcset,srcset, ACCEPT(img) ACCEPT(source))
XMACRO(start,start, ACCEPT(ol))
XMACRO(step,step, ACCEPT(input))
XMACRO(style,style, GLOBAL)
XMACRO(summary,summary, ACCEPT(table))
XMACRO(tabindex,tabindex, GLOBAL)
XMACRO(target,target, ACCEPT(a) ACCEPT(area) ACCEPT(base) ACCEPT(form))
XMACRO(title,title, GLOBAL)
XMACRO(translate,translate, GLOBAL)
XMACRO(type,type, ACCEPT(button) ACCEPT(input) ACCEPT(command) ACCEPT(embed) ACCEPT(object) ACCEPT(script) ACCEPT(source) ACCEPT(style) ACCEPT(menu))
XMACRO(usemap,usemap, ACCEPT(img) ACCEPT(input) ACCEPT(object))
XMACRO(value,value, ACCEPT(button) ACCEPT(option) ACCEPT(input) ACCEPT(li) ACCEPT(meter) ACCEPT(progress) ACCEPT(param))
XMACRO(width,width, ACCEPT(canvas) ACCEPT(embed) ACCEPT(iframe) ACCEPT(img) ACCEPT(input) ACCEPT(object) ACCEPT(video))

