#!/usr/bin/perl

my @classes;
my $class_name;
my %var_scope;
my %var_name;
my %var_type;
my %var_decl;
my %sig_args;
my %m_scope;
my %m_name;
my %m_type;
my %m_args;
my %json_types;
my @override;
my @includes;
my @includes_all;
my $to_header;
my $abstract;
my $json;
my $construct;
my $finalize;
my @uses;
my @uses_private;
my $guard;
my $separated_c;

foreach my $infile (@ARGV) {
    if ($infile eq "-c") {
        $separated_c = 1;
    } else {
        read_file($infile);
    }
}
build_classes_h();
build_forward_declare_h();

exit;

sub read_file {
    my $infile = shift @_;

    open IN, "<$infile" or die "Cannot open $infile";

    while (<IN>) {
        if (/^(abstract\s+)?(json\s+)?class\s*(\w+)\s*(\:\s*([\w]+))?/) {
            if (defined $class_name) {
                build_class();
            }

            $abstract = $1;
            $json = $2;
            $class_name = $3;
            $super = $5;
        } elsif (/guard\s+(\w+)/) {
            $guard = $1;
        } elsif (/JSON\s+([\w\*]+)\s+(\w+)/) {
            $json_types{$1} = $2;
        } elsif (/uses\s+(\w+)(\s+private)?/) {
            if (defined $class_name) {
                build_class();
            }

            if (defined $2) {
                push @uses_private, $1;
            } else {
                push @uses, $1;
            }
        } elsif (/^\/\/(.*)/) {
        } elsif (/override\s+(\w+)/) {
            push @override, $1;
        } elsif (/\s+signal\s+(\w+)\s*\(([^\)]*)\)/) {
            my $name = $1;
            my $args = $2;
            $sig_args{$name} = $args;
        } elsif (/\s+([\w]+)\s+((\w+\s+)?(\w+\s+)?[\w\*]+)\s+(\w+)\s*\(\s*([^\)]*)\)/) {
            my $scope = $1;
            my $type = $2;
            my $name = $5;
            my $args = $6;
            $m_scope{$name} = $scope;
            $m_type{$name} = $type;
            $m_args{$name} = $args;
        } elsif (/\s+([\w]+)\s+((\w+\s+)?(\w+\s+)?[\w\*]+)\s+(\w+)\s*(\:(\d+))?(\[([^\]]+)\])?/) {
            my $scope = $1;
            my $type = $2;
            my $name = $5;
            my $bits = $7;
            my $array = $9;
            $var_scope{$name} = $scope;
            $var_type{$name} = $type;
            if (defined $bits) {
                $var_decl{$name} = "Bits($bits)";
            }
            if (defined $array) {
                $var_decl{$name} = "Array($array)";
            }
        } elsif (/include\s+(all\s+)?(.*)/) {
            if (defined $class_name) {
                build_class();
            }
            if (defined $1) {
                push @includes_all, $2;
            } else {
                push @includes, $2;
            }
        } elsif (/construct/) {
            $construct = 1;
        } elsif (/finalize/) {
            $finalize = 1;
        } elsif (/([^\s](.*))/) {
            if (defined $class_name) {
                build_class();
            }
            $to_header .= "    " . $1 . " \\\n";
        }
    }

    close IN;

    if (defined $class_name) {
        build_class();
    }
}

sub build_forward_declare_h() {
    open OUT, ">forward_declare.h";
    print OUT "#ifndef __$guard" . "_FORWARD_DECLARE_H\n";
    print OUT "#define __$guard" . "_FORWARD_DECLARE_H\n";
    foreach my $file (@classes) {
        print OUT "#include \"$file" . "_class.h\"\n";
        print OUT "#include <wondermacros/objects/x/forward_declare.h>\n";
    }
    print OUT "#endif\n";
    close OUT;
}

sub build_classes_h {
    open OUT, ">classes.h";
    print OUT "#ifndef __$guard" . "_CLASSES_H\n";
    print OUT "#define __$guard" . "_CLASSES_H\n";
    foreach my $file (@classes) {
        print OUT "#include \"$file" . ".h\"\n";
    }
    print OUT "#endif\n";
    close OUT;
}

sub build_class {
    push @classes, $class_name;
    build_h();
    build_c();
    build_class_h();
}

sub build_h {
    open OUT,">$class_name" . ".h";
    my $g = uc $class_name . "_H";
    print OUT "#ifndef __$guard" . "_" . "$g\n";
    print OUT "#define __$guard" . "_" . "$g\n";
    print OUT "\n";
    print OUT "#include \"forward_declare.h\"\n";

    foreach my $file (@includes_all) {
        print OUT "#include $file\n";
    }

    if (defined $super) {
        print OUT "#include \"$super" . ".h\"\n";
    }
    foreach my $u (@uses) {
        print OUT "#include \"$u" . ".h\"\n";
    }
    print OUT "#include \"$class_name" . "_class.h\"\n";
    print OUT "#include <wondermacros/objects/x/class_declare.h>\n";
    print OUT "\n";

    print OUT "#endif /* $class_name */\n";
    close OUT;
}

sub build_c {
    if (!defined $separated_c && -e "$class_name" . ".c") {
        return;
    }
    if (defined $separated_c) {
        system "touch $class_name" . "_impl.c";
    }

    open OUT,">$class_name" . ".c";
    print OUT "#include \"forward_declare.h\"\n";
    print OUT "#include \"$class_name" . ".h\"\n";
    foreach my $u (@uses_private) {
        print OUT "#include \"$u" . ".h\"\n";
    }
    print OUT "#include \"$class_name" . "_class.h\"\n";
    print OUT "#include <wondermacros/objects/x/class_start.h>\n";
    print OUT "\n";
    if (!defined $separated_c) {
        if (defined $construct) {
            print OUT "CONSTRUCT($class_name)\n";
            print OUT "{\n";
            print OUT "}\n\n";
        }
        if (defined $finalize) {
            print OUT "FINALIZE($class_name)\n";
            print OUT "{\n";
            print OUT "}\n\n";
        }
    }
    if (!defined $separated_c) {
        foreach my $name (keys %m_type) {
            my $type = $m_type{$name};
            my $scope = $m_scope{$name};
            my $args = $m_args{$name};

            if ($args ne "") {
                print OUT "METHOD($class_name,$scope,$type,$name,($args))\n";
            } else {
                print OUT "METHOD($class_name,$scope,$type,$name)\n";
            }
            if (!defined $separated_c) {
                print OUT "{\n";
                print OUT "}\n\n";

                foreach my $name (@override) {
                    print OUT "/* Override: $name */\n";
                    print OUT "METHOD($class_name,/*FIXME:is public?*/ public,/*FIXME:is void?*/void,$name /*FIXME:has args?*/)\n";
                    print OUT "{\n";
                    print OUT "}\n\n";
                }
            }
        }
    }
    if (defined $separated_c) {
        foreach my $name (keys %m_type) {
            my $type = $m_type{$name};
            my $scope = $m_scope{$name};
            my $args = $m_args{$name};
            if (defined $separated_c) {
                print OUT "#define M__" . "$name ";
            }
            if ($args ne "") {
                print OUT "METHOD($class_name,$scope,$type,$name,($args))\n";
            } else {
                print OUT "METHOD($class_name,$scope,$type,$name)\n";
            }
        }
    }
    if (defined $separated_c) {
        print OUT "#define EXPAND_C\n";
        print OUT "#include \"$class_name" . "_impl.c\"\n\n";
        print out "#undef EXPAND_C\n";
    }
    print OUT "#include <wondermacros/objects/x/class_end.h>\n";
    close OUT;

}

sub build_class_h {
    open OUT,">$class_name" . "_class.h";

    my $c=0;
    foreach my $inc (@includes) {
        print OUT "#define INCLUDE_$c $inc\n";
        $c++;
    }
    if ($c) {
        print OUT "\n";
    }
    print OUT "#define CLASS $class_name\n";
    if (defined $super) {
        print OUT "#define SUPER $super\n";
    }
    if (defined $abstract) {
        printf OUT "#define ABSTRACT\n";
    }
    if (defined $json) {
        printf OUT "#define BUILD_JSON\n";
    }
    if (!defined $construct) {
        print OUT "#define NO_CONSTRUCT\n";
    }
    if (!defined $finalize) {
        print OUT "#define NO_DESTRUCT\n";
    }
    print OUT "\n";
    print OUT "#define $class_name" . "__define \\\n";
    if (defined $super) {
        print OUT "    /* Inherits: $super */ \\\n";
        print OUT "    $super" . "__define \\\n    \\\n";
    }

    foreach my $name (keys %var_type) {
        my $type = $var_type{$name};
        my $scope = $var_scope{$name};
        my $decl;
        if (defined $var_decl{$name}) {
            $decl = $var_decl{$name};
        }
        if (defined $json) {
            if (defined $json_types{$type}) {
                $decl .= " JSON($json_types{$type})";
            } elsif ($type=~/struct\s+(\w+)\*\*/) {
                $decl .= " JSON(json_dynamic_array_object)";
            } elsif ($type=~/struct\s+(\w+)\*/) {
                $decl .= " JSON(json_object)";
            }
        }
        if (defined $decl) {
            print OUT "    VAR($scope,$type,$name,$decl) \\\n";
        } else {
            print OUT "    VAR($scope,$type,$name) \\\n";
        }
        undef $decl;
    }

    foreach my $name (keys %sig_args) {
        print OUT "    SIGNAL($name,(" . $sig_args{$name} . ")) \\\n";
    }

    foreach my $name (keys %m_type) {
        my $type = $m_type{$name};
        my $scope = $m_scope{$name};
        my $args = $m_args{$name};
        if ($args ne "") {
            print OUT "    METHOD($class_name,$scope,$type,$name,($args)) \\\n";
        } else {
            print OUT "    METHOD($class_name,$scope,$type,$name) \\\n";
        }
    }
    foreach $name (@override) {
        print OUT "    OVERRIDE($class_name,$name) \\\n";
    }
    print OUT "    /**/\n";

    if (defined $to_header) {
        print OUT "\n#define TO_HEADER \\\n$to_header\n    /**/\n";
    }

    close OUT;

    undef $to_header;
    undef %m_scope;
    undef %m_type;
    undef %m_name;
    undef %m_args;
    undef %var_scope;
    undef %var_type;
    undef %var_name;
    undef %var_decl;
    undef %sig_args;
    undef @includes;
    undef $abstract;
    undef $super;
    undef $json;
    undef $construct;
    undef $finalize;
    undef @uses;
    undef @uses_private;
    undef @override;
    undef $class_name;
}
