name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: add boost
      run: sudo apt-get install -y libboost-all-dev
    - name: make clean
      run: make clean
    - name: make
      run: make
    - name: run tests
      run: make check
